prometheus:
  wal_directory: C:/tmp/grafana-agent-wal
  global:
    scrape_interval: 15s
  configs:
    - name: ce_agent
      scrape_configs:
        - job_name: compiler_explorer
          static_configs:
            - targets: [ "localhost:10241" ]
              labels:
                agent_hostname: "@HOSTNAME@"
                env: "@ENV@"
          relabel_configs:
            - source_labels: [ __address__ ]
              target_label: instance
              regex: (.*):(.*)
              replacement: :$2
              action: replace
      remote_write:
        - url: https://prometheus-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: "16818"
            password: "@PROM_PASSWORD@"
    - name: win_agent
      scrape_configs:
        - job_name: windows_exporter
          static_configs:
            - targets: [ "localhost:9182" ]
              labels:
                agent_hostname: "@HOSTNAME@"
                env: "@ENV@"
      remote_write:
        - url: https://prometheus-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: "16818"
            password: "@PROM_PASSWORD@"
