name: Install compiler(s)
run-name: Install ${{ inputs.compilers }}

on:
  workflow_dispatch:
    inputs:
      compilers:
        description: Things to install
        required: true
jobs:
  install:
    runs-on: [ 'self-hosted', 'ce', 'ubuntu' ]
    steps:
      - name: Start from a clean directory
        uses: AutoModality/action-clean@v1.1.0
      - uses: actions/checkout@v4
      - name: Set up environment
        run: make ce
      - name: Install ${{ github.event.inputs.compilers }}
        run: sudo bin/ce_install --check-user nobody install ${{ github.event.inputs.compilers }}
