name: Package MS compiler
run-name: Package MS compiler from ${{ inputs.url }}

on:
  workflow_dispatch:
    inputs:
      url:
        description: The Microsoft installer URL (e.g. https://aka.ms/vs/17/pre/vs_BuildTools.exe)
        required: true

jobs:
  package-ms-compiler:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - shell: pwsh
        run: .\msvc-install\gh-msvc-install.ps1 -url ${{ github.event.inputs.url }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
