name: Start Staging

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to stage'
        default: 'main'
        required: true
      buildnumber:
        description: 'Build number'
        default: 'latest'
        required: true

jobs:
  startstaging:
    runs-on: ['admin']

    steps:
    - name: Update infra
      run: cd /home/ubuntu/infra && git pull && make ce
    - name: Blue-green deploy to staging
      run: ce --env staging blue-green deploy --branch ${{ github.event.inputs.branch }} --skip-confirmation --no-notify ${{ github.event.inputs.buildnumber }}
